name: "Generate Human-Readable Release Notes"
description: "Converts raw release notes into a human-readable format using OpenAI GPT."
inputs:
  release_notes:
    description: "Raw release notes to be converted."
    required: true
outputs:
  human_readable_notes:
    description: "The converted, human-readable release notes."
runs:
  using: "node12"
  main: "dist/index.bundle.js"
